/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blooddonate;

/**
 *
 * @author SR
 */
public class AcceptedPanel extends javax.swing.JFrame {

    public String Name,AddressD,HospitalN;
    public String PhoneN;
    public AcceptedPanel() {
        initComponents();
        this.setBounds(100,50,900,700);
    }
    public void SetValue(String Name,String PhoneN,String AddressD,String HospitalN){
        this.Name=Name;
        this.PhoneN=PhoneN;
        this.AddressD=AddressD;
        this.HospitalN=HospitalN;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Accepted = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Admin = new javax.swing.JButton();
        NameN = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BACKP = new javax.swing.JButton();
        NameText = new javax.swing.JLabel();
        PH = new javax.swing.JLabel();
        AddressF = new javax.swing.JLabel();
        HospitalNAme = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Accepted.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 24)); // NOI18N
        Accepted.setText("Your Request Is Approved...");
        jPanel1.add(Accepted);
        Accepted.setBounds(30, 300, 330, 25);

        jLabel1.setText("Donner Is ready For Donet Blood.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 330, 290, 20);

        jLabel2.setText("If You Have Any Problem, Please Contact ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 420, 240, 16);

        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jPanel1.add(Admin);
        Admin.setBounds(770, 420, 90, 20);

        NameN.setText("Name:");
        jPanel1.add(NameN);
        NameN.setBounds(30, 20, 38, 16);

        Phone.setText("Phone:");
        jPanel1.add(Phone);
        Phone.setBounds(30, 60, 40, 16);

        jLabel3.setText("Address:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 70, 16);

        jLabel4.setText("Hospital: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 160, 60, 16);

        jLabel5.setText("Your Request Is Processing.......");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 250, 240, 50);

        BACKP.setText("BACK");
        BACKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKPActionPerformed(evt);
            }
        });
        jPanel1.add(BACKP);
        BACKP.setBounds(40, 415, 160, 40);

        NameText.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                NameTextAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(NameText);
        NameText.setBounds(100, 20, 500, 20);

        PH.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PHAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(PH);
        PH.setBounds(100, 60, 480, 20);

        AddressF.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                AddressFAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(AddressF);
        AddressF.setBounds(120, 110, 310, 20);

        HospitalNAme.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                HospitalNAmeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(HospitalNAme);
        HospitalNAme.setBounds(120, 160, 370, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonate/accepted.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(610, -30, 320, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        Admin AD=new Admin();
        AD.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void BACKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKPActionPerformed
        // TODO add your handling code here:
        BloodDonation donation= new BloodDonation();
        donation.setVisible(true);
    }//GEN-LAST:event_BACKPActionPerformed

    private void NameTextAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_NameTextAncestorAdded
        // TODO add your handling code here:
        NameText.setText(Name);
    }//GEN-LAST:event_NameTextAncestorAdded

    private void PHAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PHAncestorAdded
        // TODO add your handling code here:
        PH.setText(PhoneN);
    }//GEN-LAST:event_PHAncestorAdded

    private void AddressFAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_AddressFAncestorAdded
        // TODO add your handling code here:
        AddressF.setText(AddressD);
    }//GEN-LAST:event_AddressFAncestorAdded

    private void HospitalNAmeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_HospitalNAmeAncestorAdded
        // TODO add your handling code here:
        HospitalNAme.setText(HospitalN);
    }//GEN-LAST:event_HospitalNAmeAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceptedPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceptedPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceptedPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceptedPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceptedPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accepted;
    private javax.swing.JLabel AddressF;
    private javax.swing.JButton Admin;
    private javax.swing.JButton BACKP;
    private javax.swing.JLabel HospitalNAme;
    private javax.swing.JLabel NameN;
    private javax.swing.JLabel NameText;
    private javax.swing.JLabel PH;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
