/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blooddonate;

/**
 *
 * @author SR
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setBounds(100,50,900,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Send = new javax.swing.JTextField();
        Sub = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        LI = new javax.swing.JButton();
        Desig = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        empty = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NameR = new javax.swing.JTextField();
        enterS = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel16.setText("jLabel16");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonate/report.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 217, 168));
        jPanel1.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Discribe Your Problem");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 190, 220, 32);

        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        jPanel1.add(Send);
        Send.setBounds(80, 230, 247, 180);

        Sub.setText("Submit");
        Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubActionPerformed(evt);
            }
        });
        jPanel1.add(Sub);
        Sub.setBounds(180, 450, 152, 25);

        jLabel10.setText("/");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 500, 10, 20);

        jPanel2.setBackground(new java.awt.Color(22, 15, 247));
        jPanel2.setLayout(null);

        jLabel13.setBackground(new java.awt.Color(255, 51, 51));
        jLabel13.setFont(new java.awt.Font("Adobe Garamond Pro", 2, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 51));
        jLabel13.setText("Admin Panel Login");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 23, 225, 25);

        jLabel14.setForeground(new java.awt.Color(102, 255, 102));
        jLabel14.setText("Enter Designation");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(12, 61, 100, 16);

        jLabel15.setForeground(new java.awt.Color(102, 255, 102));
        jLabel15.setText("Enter Admin Password");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 140, 129, 16);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(10, 170, 181, 22);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(10, 90, 165, 22);

        LI.setText("Log In");
        LI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIActionPerformed(evt);
            }
        });
        jPanel2.add(LI);
        LI.setBounds(20, 240, 90, 25);

        Desig.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(Desig);
        Desig.setBounds(10, 120, 170, 10);

        Pass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(Pass);
        Pass.setBounds(10, 200, 180, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonate/adminlogin.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 320, 290);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(570, 0, 320, 290);

        empty.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(empty);
        empty.setBounds(90, 420, 250, 20);

        jLabel17.setForeground(new java.awt.Color(0, 255, 255));
        jLabel17.setText("Enter Your Name");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(80, 110, 280, 16);

        NameR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameRActionPerformed(evt);
            }
        });
        jPanel1.add(NameR);
        NameR.setBounds(80, 130, 220, 22);

        enterS.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(enterS);
        enterS.setBounds(80, 160, 220, 20);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 450, 90, 25);

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setText("Phone Number: ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 10, 93, 30);

        jLabel4.setText("+880192866221");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(110, 10, 166, 30);

        jLabel5.setText("Gmail:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(60, 40, 38, 30);

        jLabel7.setText("Facebook:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 70, 59, 20);

        jLabel12.setText("fb.me/blooddonation225");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(110, 70, 139, 16);

        jLabel9.setText(" m.me/blooddonation225");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(110, 90, 143, 20);

        jLabel6.setText(" blooddonation225@gmail.com");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(110, 40, 192, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(570, 450, 320, 140);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonate/new.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 890, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().trim().isEmpty() && jPasswordField1.getText().trim().isEmpty()){
            Desig.setText("Enter Something");
            Pass.setText("Enter Something");
        }
        else if(jTextField2.getText().trim().isEmpty()){
            Desig.setText("Enter Something");
        }
        else if(jPasswordField1.getText().trim().isEmpty()){
            Pass.setText("Enter Something");
        }
        else if( jTextField2.getText().equalsIgnoreCase("Admin")){
            if(jPasswordField1.getText().equals("12345")){
                AdminDeshboard AD= new AdminDeshboard();
                AD.setVisible(true);
            }
            else{
                Pass.setText("wrong password or you are not admin");
            }
        }
        
    }//GEN-LAST:event_LIActionPerformed

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed

    }//GEN-LAST:event_SendActionPerformed

    private void SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubActionPerformed
        // TODO add your handling code here:
        if(NameR.getText().trim().isEmpty() && Send.getText().trim().isEmpty()){
            enterS.setText("Enter Name before Submit");
            empty.setText("Enter something before Submit");
        }
        else if(NameR.getText().trim().isEmpty()){
            enterS.setText("Enter Name before Submit");
        }
        else if(Send.getText().trim().isEmpty()){
          empty.setText("Enter something before Submit");  
        }
        else{
            ReportAndSuggestion RAS= new ReportAndSuggestion();
            RAS.setVisible(true);
            RAS.ReportAS(NameR.getText(), Send.getText());
        }
        
    }//GEN-LAST:event_SubActionPerformed

    private void NameRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DonnorPanel donnor= new DonnorPanel();
        donnor.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desig;
    private javax.swing.JButton LI;
    private javax.swing.JTextField NameR;
    private javax.swing.JLabel Pass;
    private javax.swing.JTextField Send;
    private javax.swing.JButton Sub;
    private javax.swing.JLabel empty;
    private javax.swing.JLabel enterS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
