/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blooddonate;

/**
 *
 * @author SR
 */
public class BloodDonation extends javax.swing.JFrame {

    /**
     * Creates new form BloodDonation
     */
    public BloodDonation() {
        initComponents();
        this.setBounds(100,50,900,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ProblemBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Howmanybag1 = new javax.swing.JRadioButton();
        Howmanybag3 = new javax.swing.JRadioButton();
        Howmanybag2 = new javax.swing.JRadioButton();
        Howmanybag4 = new javax.swing.JRadioButton();
        Hospital = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AddressD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        district = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Thana = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        name_user = new javax.swing.JLabel();
        phone_user = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        Problem = new javax.swing.JLabel();
        DistrictBox = new javax.swing.JLabel();
        HospitalN = new javax.swing.JLabel();
        ThanaN = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Apossitive = new javax.swing.JRadioButton();
        Anegetive = new javax.swing.JRadioButton();
        Bposstitve = new javax.swing.JRadioButton();
        Bnegetive = new javax.swing.JRadioButton();
        Opossitive = new javax.swing.JRadioButton();
        Onegetive = new javax.swing.JRadioButton();
        ABPossitive = new javax.swing.JRadioButton();
        ABNegetive = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Welcome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 264, 31);

        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Enter Your Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 40, 151, 31);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel1.add(Name);
        Name.setBounds(90, 70, 151, 22);

        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Enter Your Phone Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 120, 151, 32);
        jPanel1.add(Phone);
        Phone.setBounds(90, 150, 151, 22);

        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Discribe Your Problem");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 210, 151, 16);
        jPanel1.add(ProblemBox);
        ProblemBox.setBounds(90, 240, 151, 74);

        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("How Many Bags");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 360, 151, 20);

        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Enter Hospital Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 260, 187, 20);

        buttonGroup1.add(Howmanybag1);
        Howmanybag1.setText("1");
        Howmanybag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Howmanybag1ActionPerformed(evt);
            }
        });
        jPanel1.add(Howmanybag1);
        Howmanybag1.setBounds(90, 400, 35, 25);

        buttonGroup1.add(Howmanybag3);
        Howmanybag3.setText("2");
        Howmanybag3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Howmanybag3ActionPerformed(evt);
            }
        });
        jPanel1.add(Howmanybag3);
        Howmanybag3.setBounds(90, 450, 35, 25);

        buttonGroup1.add(Howmanybag2);
        Howmanybag2.setText("3");
        Howmanybag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Howmanybag2ActionPerformed(evt);
            }
        });
        jPanel1.add(Howmanybag2);
        Howmanybag2.setBounds(160, 400, 35, 25);

        buttonGroup1.add(Howmanybag4);
        Howmanybag4.setText("4 or More");
        Howmanybag4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Howmanybag4ActionPerformed(evt);
            }
        });
        jPanel1.add(Howmanybag4);
        Howmanybag4.setBounds(160, 450, 85, 25);
        jPanel1.add(Hospital);
        Hospital.setBounds(380, 290, 220, 22);

        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Delivery Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 340, 170, 30);

        AddressD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressDActionPerformed(evt);
            }
        });
        jPanel1.add(AddressD);
        AddressD.setBounds(380, 380, 150, 22);

        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("Enter Your District");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 50, 103, 16);
        jPanel1.add(district);
        district.setBounds(380, 90, 143, 22);

        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("Enter Your Thana Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(380, 160, 143, 16);
        jPanel1.add(Thana);
        Thana.setBounds(380, 190, 143, 22);

        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setText("Enter Postal code");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 440, 160, 30);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(380, 480, 131, 22);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(660, 620, 193, 50);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(30, 620, 120, 50);

        name_user.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(name_user);
        name_user.setBounds(90, 100, 250, 20);
        jPanel1.add(phone_user);
        phone_user.setBounds(90, 180, 160, 0);

        PhoneNumber.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(PhoneNumber);
        PhoneNumber.setBounds(90, 180, 270, 20);

        Problem.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(Problem);
        Problem.setBounds(90, 320, 240, 20);

        DistrictBox.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(DistrictBox);
        DistrictBox.setBounds(380, 130, 200, 20);

        HospitalN.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(HospitalN);
        HospitalN.setBounds(380, 320, 260, 20);

        ThanaN.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(ThanaN);
        ThanaN.setBounds(380, 230, 240, 20);

        address.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(address);
        address.setBounds(380, 420, 260, 20);

        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setText("Blood Group :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 570, 100, 16);

        buttonGroup2.add(Apossitive);
        Apossitive.setText("A+");
        jPanel1.add(Apossitive);
        Apossitive.setBounds(180, 570, 45, 25);

        buttonGroup2.add(Anegetive);
        Anegetive.setText("A-");
        jPanel1.add(Anegetive);
        Anegetive.setBounds(260, 570, 41, 25);

        buttonGroup2.add(Bposstitve);
        Bposstitve.setText("B+");
        jPanel1.add(Bposstitve);
        Bposstitve.setBounds(320, 570, 43, 25);

        buttonGroup2.add(Bnegetive);
        Bnegetive.setText("B-");
        jPanel1.add(Bnegetive);
        Bnegetive.setBounds(400, 570, 41, 25);

        buttonGroup2.add(Opossitive);
        Opossitive.setText("O+");
        jPanel1.add(Opossitive);
        Opossitive.setBounds(460, 570, 45, 25);

        buttonGroup2.add(Onegetive);
        Onegetive.setText("O-");
        jPanel1.add(Onegetive);
        Onegetive.setBounds(530, 570, 43, 25);

        buttonGroup2.add(ABPossitive);
        ABPossitive.setText("AB+");
        jPanel1.add(ABPossitive);
        ABPossitive.setBounds(600, 570, 50, 25);

        buttonGroup2.add(ABNegetive);
        ABNegetive.setText("AB-");
        jPanel1.add(ABNegetive);
        ABNegetive.setBounds(670, 570, 49, 25);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blooddonate/Signup.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(-2, 0, 900, 880);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CoverPage obj= new CoverPage();
        obj.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void AddressDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressDActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        if(Name.getText().trim().isEmpty()){
            name_user.setText("Enter something");
        }
        else if(Phone.getText().trim().isEmpty()){
            PhoneNumber.setText("Phone Number Is Empty");
        }
        else if(ProblemBox.getText().trim().isEmpty()){
            Problem.setText("Box Is Empty");
        }
        else if(district.getText().trim().isEmpty()){
            DistrictBox.setText("Box is empty");
        }
        else if(AddressD.getText().trim().isEmpty()){
            HospitalN.setText("Box Is Empty");
        }
        else if(Thana.getText().trim().isEmpty()){
            ThanaN.setText("Box is  Empty");
        }
        else if(AddressD.getText().trim().isEmpty()){
            address.setText("Phone Number Is Empty");
        }
        else{
            AcceptedPanel AP= new AcceptedPanel();
            
            AP.SetValue(Name.getText(), Phone.getText(), AddressD.getText(), AddressD.getText());
            AP.setVisible(true);
        }
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void Howmanybag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Howmanybag1ActionPerformed
        
    }//GEN-LAST:event_Howmanybag1ActionPerformed

    private void Howmanybag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Howmanybag2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Howmanybag2ActionPerformed

    private void Howmanybag3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Howmanybag3ActionPerformed
        // TODO add your handling code here:
       ;
    }//GEN-LAST:event_Howmanybag3ActionPerformed

    private void Howmanybag4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Howmanybag4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Howmanybag4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodDonation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ABNegetive;
    private javax.swing.JRadioButton ABPossitive;
    private javax.swing.JTextField AddressD;
    private javax.swing.JRadioButton Anegetive;
    private javax.swing.JRadioButton Apossitive;
    private javax.swing.JButton Back;
    private javax.swing.JRadioButton Bnegetive;
    private javax.swing.JRadioButton Bposstitve;
    private javax.swing.JLabel DistrictBox;
    private javax.swing.JTextField Hospital;
    private javax.swing.JLabel HospitalN;
    private javax.swing.JRadioButton Howmanybag1;
    private javax.swing.JRadioButton Howmanybag2;
    private javax.swing.JRadioButton Howmanybag3;
    private javax.swing.JRadioButton Howmanybag4;
    private javax.swing.JTextField Name;
    private javax.swing.JRadioButton Onegetive;
    private javax.swing.JRadioButton Opossitive;
    private javax.swing.JTextField Phone;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel Problem;
    private javax.swing.JTextField ProblemBox;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField Thana;
    private javax.swing.JLabel ThanaN;
    private javax.swing.JLabel address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JTextField district;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel name_user;
    private javax.swing.JLabel phone_user;
    // End of variables declaration//GEN-END:variables
}
